name: AppScanSbom
on:
  push:
    branches:
      - master # or the name of your main branch
  schedule:
    - cron: '0 0 * * *' # Sets to scan every day at midnight.
    # It is recommended to change the schedule to a random time.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install cyclonedx
        shell: bash
        run: |
          pip install cyclonedx-bom
      - name: Generate SBOM
        shell: bash
        run: |
          cyclonedx-py -r -o bom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: SBOM Artifact
          path: bom.xml